language: rust
rust: stable
dist: xenial
sudo: false

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

jobs:
  include:
    - stage: "Check"
      name: "Cargo Check"
      script: "cargo check"