[package]
name = "chaos_equations"
version = "0.2.0"
authors = ["Ryan Christian <ryanchristian4427@gmail.com>"]
edition = "2018"

[dependencies]
glium = "*"
rand = "0.7.0"
glium_text = { git = "https://github.com/RyanChristian4427/glium_text" }
cgmath = "0.16"